version: "3"
services:
  app:
    build:
      context: ./server
      dockerfile: ./.Dockerfile
    volumes:
      - ./server/plugins:/plugins
      - ./server/server.properties:/server.properties
    ports:
      - "35351:25565"
      - "4567:4567"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo
    ports:
      - "33333:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: minebirds_user
      MONGO_INITDB_ROOT_PASSWORD: minebirds_pass
      MONGO_INITDB_DATABASE: minebirds_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
